from setuptools import find_packages, setup

package_name = 'py_pubsub'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='vboxuser',
    maintainer_email='vboxuser@todo.todo',
    description='Examples of minimal publisher/subscriber using rclpy',
    license='Apache License 2.0',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
                'talker = py_pubsub.publisher_member_function:main',
                'listener = py_pubsub.subscriber_member_function:main',
                'listener_float = py_pubsub.subscriber_member_function_FLOAT:main',
                'talker_float = py_pubsub.publisher_member_function_FLOAT:main',
                'talker_uint8 = py_pubsub.publisher_member_function_UINT8:main',
                'listener_uint8 = py_pubsub.subscriber_member_function_UINT8:main',
                'talker_float_array = py_pubsub.publisher_member_function_FLOAT32_array:main',
                'listener_float_array = py_pubsub.subscriber_member_function_FLOAT32_array:main',
                'battery_resistance_estimator = py_pubsub.battery_resistance_estimator:main',
                'battery_resistance_estimator1 = py_pubsub.battery_resistance_estimator1:main',
                'battery_resistance_estimator2 = py_pubsub.battery_resistance_estimator2:main',
                'battery_resistance_estimator3 = py_pubsub.battery_resistance_estimator3:main',
                'battery_resistance_logger = py_pubsub.battery_resistance_logger:main',
                'battery_resistance_estimator4 = py_pubsub.battery_resistance_estimator4:main',
                'battery_resistance_estimator5 = py_pubsub.battery_resistance_estimator5:main',
                'battery_resistance_estimator6 = py_pubsub.battery_resistance_estimator6:main',
                'battery_resistance_estimator7 = py_pubsub.battery_resistance_estimator7:main',
                'battery_resistance_estimator8 = py_pubsub.battery_resistance_estimator8:main',
                'battery_resistance_estimator9 = py_pubsub.battery_resistance_estimator9:main',
                'battery_resistance_estimator10 = py_pubsub.battery_resistance_estimator10:main',
                'battery_resistance_estimator11 = py_pubsub.battery_resistance_estimator11:main',
                'battery_resistance_estimator12 = py_pubsub.battery_resistance_estimator12:main',
                'battery_resistance_logger_FSG = py_pubsub.battery_resistance_logger_FSG:main',
                'battery_resistance_estimator13 = py_pubsub.battery_resistance_estimator13:main',
                'battery_resistance_estimator14 = py_pubsub.battery_resistance_estimator14:main',
        ],
    },
)
